
INSERT INTO listings (user_id, title, description, image, date_created, price, behaviour, category)
VALUES
(6, 'Jake', 'Jake is hoping to find a home all his own. He would love a home where he can have some space to curl up in a cozy bed or watch what’s happening outside. Jake would prefer to be the solo feline in the home. No other cheetahs please. He is best suited for an adult home or with children over 12.', 'http://upload.wikimedia.org/wikipedia/commons/b/bc/Koushki_2.jpg', '2019-04-24 12:41:49', '8000', 'lazy', 'cheetah'),

(2, 'Snickerdoodle', 'Snickerdoodle is a much fun as his name suggests! He loves to play, follow you around and help you work on the computer...meaning he’ll lay all over the keyboard while you work. This friendly guy loves affection and will start up his purrrrr machine with a few scritches from his favourite person.', 'http://upload.wikimedia.org/wikipedia/commons/8/81/2012_Suedchinesischer_Tiger.JPG', '2019-10-21 23:53:43', '10000', 'cuddly', 'tiger'),

(3, 'Buster', 'Buster is a beautiful long-haired senior looking for some loving cuddles and a quiet home purr-fect for long lion naps. He is affectionate and loves his pets. Being a senior he’s pretty calm and undemanding. He has a long coat that will need to be brushed to prevent any tangles but he doenst mind a good brushing session.', 'http://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg', '2019-08-07 10:09:42', '5000', 'calm', 'lion'),

(4, 'Sylvester', 'Sylvester is a lovely senior jaguar who is looking for a five star retirement resort. He is a handsome gentleman who loves to relax in his comfy bed. His ideal home would be quiet, calm and give him the time to settle in. Senior jaguars make wonderful companions.', 'http://live.staticflickr.com/4563/37956986074_1ebc8ae7c2_b.jpg', '2019-06-10 23:50:58', '6000', 'quiet', 'jaguar'),

(5, 'Pepper', 'Looking for a feline friend to talk to? Pepper is just the leopard for you! Pepper is a bit of a Chatty Cathy, she enjoys deep conversations about life and it’s little mysteries. That’s not the only thing she enjoys, though! She also loves attention, cuddles, and a warm lap to lay on.', 'https://upload.wikimedia.org/wikipedia/commons/0/06/Leopard_Male_Nagarhole.jpg', '2019-10-23 00:13:52', '9000', 'active', 'leopard'),

(7, 'Milo', 'Milo is a very shy 9 month old female cougar with a medium black and white coat. Milo would perhaps do well with a socialized cougar companion, who can teach her that humans are safe and kind. We feel given time and patience she may improve in a home that could provide this pretty girl with a calm and relaxed environment.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Mountain_Lion_in_Glacier_National_Park.jpg/1200px-Mountain_Lion_in_Glacier_National_Park.jpg', '2019-09-29 18:35:46', '7000', 'shy', 'cougar'),

(1, 'Daisy', 'Daisy loves being inside with her family, staying comfortable and safe. Daisy is used to being the only animal and would do best in a home with no other animals, she likes to be the queen of her castle. She can be startled by loud noises and may be a bit shy at first until comfortable.', 'https://cdn.britannica.com/98/152298-050-8E45510A/Cheetah.jpg', '2019-07-13 14:58:04', '12000', 'antisocial', 'cheetah'),

(5, 'Cleo', 'Cleo would love a quiet home with her own place to sleep the days away. She loves raw food and prefers it to be served multiple times daily so it is always fresh! Don’t be deceived by her pouty look, she’s actually a very gentle, affectionate and sweet lady with a crackly roar and one white whisker.', 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Bengal_Tiger.jpg/1024px-Bengal_Tiger.jpg', '2019-09-04 13:09:35', '7500', 'gentle', 'tiger'),

(8, 'Angel', 'Angel frequently hunts for her favourite toys, and brings them to you as gifts. A funny thing to note: Angel also likes to look out from windows. She is best suited to a calm, quiet home', 'http://live.staticflickr.com/5254/5454505643_b399953e2a_b.jpg', '2019-09-23 11:28:04', '11000', 'silly', 'lion'),

(1, 'Dusty', 'Dusty is a strikingly handsome male jaguar. He is quite shy and would do best in a home where he was the only jaguar with no small children.', 'https://www.wwf.org.uk/sites/default/files/styles/hero_s/public/2019-04/Jaguar%20in%20a%20tree%2C%20Brazil%20%C2%A9%20Y.-J.%20Rey-Millet%20%20WWF%20_2.jpg?h=c1795639&itok=vljGjIN1', '2019-08-19 03:23:49', '9000', 'grumpy', 'jaguar'),

(2, 'Oscar', 'Oscar likes to snooze with you in the morning, and get some belly rubs while hes there. He doesnt mind getting picked up occasionally, but hes not a hugger in general. Hes quite affectionate though, and just shows it in different ways.', 'http://live.staticflickr.com/8166/7233839982_92768e39ab_b.jpg', '2019-05-09 00:44:16', '13000', 'territorial', 'leopard'),

(3, 'Misty', 'Misty and Coco haved lived together for 4 years. We would love to place these ladies together if we can find that very special home for them. They lived with a lion in their previous home. Misty is more easy going than Coco.', 'http://www.publicdomainpictures.net/pictures/40000/nahled/cougar-1362322877sbZ.jpg', '2019-10-05 16:03:11', '4000', 'easygoing', 'cougar'),

(4, 'Coco', 'Misty and Coco haved lived together for 4 years. We would love to place these ladies together if we can find that very special home for them. Coco is more reserved until you get to know her. She may be more shy but she is also more playful', 'http://www.publicdomainpictures.net/pictures/300000/nahled/cheetah-watching.jpg', '2020-04-01 17:37:41', '4000', 'playful', 'cheetah'),

(9, 'Lucy', 'Lucy is looking for a new home because she and her other tiger friend arent getting along. She is a pretty lady that would suit to be an only tiger. She is healthy and quite affectionate on her own but can be shy.', 'http://upload.wikimedia.org/wikipedia/commons/6/62/Panthera_tigris_sumatran_subspecies.jpg', '2019-12-25 04:19:51', '7500', 'shy', 'tiger'),

(4, 'Simba', 'Simba is a rowdy, independent little cub who likes to romp and play. Simba did not like grubs when he was younger but has since come to like them. His favourite saying is Hakuna Matata - whatever that means. Simba will one day become the King of the Pride Lands and ruler of Pride Rock.', 'http://vignette.wikia.nocookie.net/theamazingworldofcartoonsandgames/images/a/a8/MTS_Camalus28-1157913-Screenshot-20.jpg', '2019-09-05 19:22:39', '16000', 'independant', 'lion'),

(5, 'Max', 'Max came to us after his owners were no longer able to care for him. He is new to us and is still quite scared and timid from his transition from his old home to us, he is not aggressive just apprehensive. We suspect he will be timid at first but will warm up to a new family that has patience with him.', 'http://upload.wikimedia.org/wikipedia/commons/d/de/On%C3%A7a-pintada_%28Panthera_onca%29_-_Jaguar.jpg', '2019-10-17 10:57:11', '10500', 'nervous', 'jaguar'),

(6, 'Monty', 'Monty was brought into us after he was hanging around in someones backyard for about three weeks. He can have a bit of feisty side to him so we recommend a home without children and one where he would be an only pet. Monty has warmed up to us the more time he spends with our staff and he will warm up to a loving home as well.', 'https://uganda365.com/wp-content/uploads/2018/12/african-leopard-facts.jpg', '2019-08-15 09:52:05', '6000', 'feisty', 'leopard'),

(11, 'Whiskers', 'This large adult tiger is female.  She has a short white coat with many cinnamon chinchilla spots.  She has a short, narrow face and is quite muscular.  She is especially fond of chicken, is very lazy, and is very shy.', 'http://upload.wikimedia.org/wikipedia/commons/a/a4/White-tiger-2407799_1280.jpg', '2019-04-13 20:51:44', '3500', 'curious', 'tiger'),

(2, 'Buddy', 'This average-sized adult lion is male.  He has a short white coat with a matching mane and tail with a spot on his back.  He has a medium-length, average-width face and is fairly muscular.  He is a picky eater, is very playful, and is cautious around strangers.', 'https://2.bp.blogspot.com/-mjomzPFsAQ4/UX6OhLM5fBI/AAAAAAAAaX4/-wrRW5FKZRY/s1600/White+lion.jpg', '2019-12-07 04:10:08', '5500', 'cautious', 'lion'),

(3, 'Toby', 'Toby is always yawning, or laughing. We cant tell which. He loves being close to water, and will lay by the river for hours. He has a short, broad face and is fairly muscular.  He is very excitable, and will jump on any available lap.', 'https://i.pinimg.com/originals/e5/57/54/e55754cadbf236f640bae3b0cd52a50c.jpg', '2019-04-15 16:13:44', '6000', 'excitable', 'jaguar'),

(4, 'Rusty', 'Rusty has 4 legs and a tail, and also spots which shouldnt surprise anyone as he is a leapard after all. He has a medium-length, average-width face and is quite thin.  He likes to roll around, and lay in the sun.', 'https://media.mehrnews.com/d/2018/03/18/4/2744865.jpg', '2020-01-11 15:59:05', '4500', 'lazy', 'leopard'),

(5, 'Pumpkin', 'Pumpkin has a short, narrow face and is of average weight. Here she is playing in the snow. When she was a kitten, she ran out into a pumpkin patch and we couldnt find her for over an hour. Thats how she got her name.  She is very friendly.', 'https://3xnhi43vikn244hoyg160zl4-wpengine.netdna-ssl.com/wp-content/uploads/2019/12/19709322_web1_Cougar-WildSafeBC.jpg', '2020-03-10 10:11:37', '5000', 'friendly', 'cougar');
